<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2ecf2cf4-4c81-4310-91a8-3eead51ebaa0</testSuiteGuid>
   <testCaseLink>
      <guid>2f70fa58-60ee-4219-bdd0-7f9389bf17a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTests/TC05 - Name of employees are ordered by ascending of alphabets when clicking on Name header</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>93f5b374-66fc-489e-b80e-281fd7f33973</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/UserData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>93f5b374-66fc-489e-b80e-281fd7f33973</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>User</value>
         <variableId>26ad4236-35f5-4d9c-bcc6-b979f4defc7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>93f5b374-66fc-489e-b80e-281fd7f33973</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Pass</value>
         <variableId>308dc0a9-7a47-4fb0-be69-ced4d093f58e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
