<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_user admin_c-avatar-img</name>
   <tag></tag>
   <elementGuidId>2904c43f-0cc9-4138-aaa6-e2d0b6c7ce92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.c-avatar-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='user@email.com']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/img/avatars/user.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>user@email.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-avatar-img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ah-root[1]/ah-general-info[1]/div[@class=&quot;c-app&quot;]/div[@class=&quot;c-wrapper c-fixed-components&quot;]/ah-header[1]/header[@class=&quot;c-header c-header-light c-header-fixed c-header-with-subheader&quot;]/ul[@class=&quot;c-header-nav ml-auto mr-4&quot;]/li[@class=&quot;c-header-nav-item dropdown show&quot;]/a[@class=&quot;c-header-nav-link&quot;]/div[@class=&quot;c-avatar&quot;]/img[@class=&quot;c-avatar-img&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='user@email.com']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
   </webElementXpaths>
</WebElementEntity>
