<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_wrong_name</name>
   <tag></tag>
   <elementGuidId>0efcccc5-e1e4-4052-9948-1c4fbfc10289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody//a[not(contains(.,'${name}'))]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//tbody//a[not(contains(.,'ab'}))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody//a[not(contains(.,'ab'}))]</value>
   </webElementProperties>
</WebElementEntity>
